Changes Made fist code

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,4 +6,13 @@ jobs:
     steps:
       - name: Say hello
         run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye !"    
 
